In [1]:
import pandas as pd
import numpy as np
import pickle

In [2]:
PICKLE_PATH = '../augmented_datasets/pickles/hopkins_conf_gf0304.pkl'

RESULT_PATH = '../augmented_datasets/pickles/hopkins_conf_gf0304_GDP.pkl'

In [3]:
hopkins_conf = pd.DataFrame()

with open(PICKLE_PATH, 'rb') as file:
    hopkins_conf = pd.read_pickle(file)

hopkins_conf

                                  Province_State Country_Region  avg_m_tmp  \
coordinate           information
(-41.4545, 145.9707) data               Tasmania      Australia  15.466667
                     avg_d_RH                NaN            NaN        NaN
                     avg_d_precip            NaN            NaN        NaN
                     avg_d_tmp               NaN            NaN        NaN
                     avg_d_wind              NaN            NaN        NaN
...                                          ...            ...        ...
(64.9631, -19.0208)  data                    NaN        Iceland  -2.230159
                     avg_d_RH                NaN            NaN        NaN
                     avg_d_precip            NaN            NaN        NaN
                     avg_d_tmp               NaN            NaN        NaN
                     avg_d_wind              NaN            NaN        NaN

                                    avg_m_RH  avg_m_precip  avg_m_wind  \
coordinate           information
(-41.4545, 145.9707) data          68.818182           0.0   18.469697
                     avg_d_RH            NaN           NaN         NaN
                     avg_d_precip        NaN           NaN         NaN
                     avg_d_tmp           NaN           NaN         NaN
                     avg_d_wind          NaN           NaN         NaN
...                                      ...           ...         ...
(64.9631, -19.0208)  data          78.571429           0.0   16.523810
                     avg_d_RH            NaN           NaN         NaN
                     avg_d_precip        NaN           NaN         NaN
                     avg_d_tmp           NaN           NaN         NaN
                     avg_d_wind          NaN           NaN         NaN

                                   Max_Cases   first_7 last relevant date  \
coordinate           information
(-41.4545, 145.9707) data               47.0  1.333333          3/27/2020
                     avg_d_RH            NaN       NaN
                     avg_d_precip        NaN       NaN
                     avg_d_tmp           NaN       NaN
                     avg_d_wind          NaN       NaN
...                                      ...       ...                ...
(64.9631, -19.0208)  data              890.0  1.680000          3/27/2020
                     avg_d_RH            NaN       NaN
                     avg_d_precip        NaN       NaN
                     avg_d_tmp           NaN       NaN
                     avg_d_wind          NaN       NaN

                                    Max_Date  ... 3/18/2020  3/19/2020  \
coordinate           information              ...
(-41.4545, 145.9707) data          3/26/2020  ...      10.0       10.0
                     avg_d_RH                 ...      82.0       93.0
                     avg_d_precip             ...       0.0        0.0
                     avg_d_tmp                ...      16.5       14.9
                     avg_d_wind               ...      18.6        8.4
...                                      ...  ...       ...        ...
(64.9631, -19.0208)  data          3/27/2020  ...     250.0      330.0
                     avg_d_RH                 ...      77.0       75.0
                     avg_d_precip             ...       0.0        0.0
                     avg_d_tmp                ...      -1.0       -6.0
                     avg_d_wind               ...      13.4       13.6

                                   3/20/2020  3/21/2020  3/22/2020  3/23/2020  \
coordinate           information
(-41.4545, 145.9707) data               10.0       16.0       22.0       28.0
                     avg_d_RH           81.0       73.0       68.0       64.0
                     avg_d_precip        0.0        0.0        0.0        0.0
                     avg_d_tmp          14.9       14.1       12.8       10.6
                     avg_d_wind         21.2       13.5       14.4        9.8
...                                      ...        ...        ...        ...
(64.9631, -19.0208)  data              409.0      473.0      568.0      588.0
                     avg_d_RH           67.0       67.0       66.0       69.0
                     avg_d_precip        0.0        0.0        0.0        0.0
                     avg_d_tmp           2.3        2.4        1.9        3.0
                     avg_d_wind         36.3       29.4       27.8       35.3

                                   3/24/2020  3/25/2020  3/26/2020  3/27/2020
coordinate           information
(-41.4545, 145.9707) data               28.0       36.0       47.0       47.0
                     avg_d_RH           74.0       74.0       68.0       74.0
                     avg_d_precip        0.0        0.0        0.0        0.0
                     avg_d_tmp          11.1       12.3       11.2       13.5
                     avg_d_wind         10.1        8.5       15.2        6.8
...                                      ...        ...        ...        ...
(64.9631, -19.0208)  data              648.0      737.0      802.0      890.0
                     avg_d_RH           63.0       62.0       59.0       64.0
                     avg_d_precip        0.0        0.0        0.0        0.0
                     avg_d_tmp           1.6        1.6        1.5       -0.9
                     avg_d_wind         25.6       16.6       24.8       12.5

[895 rows x 82 columns]

In [4]:
test = pd.DataFrame()
with open(RESULT_PATH, 'rb') as file:
    test = pd.read_pickle(file)    
test

                                  Province_State Country_Region          GDP  \
coordinate           information
(-41.4545, 145.9707) data               Tasmania      Australia  57373.68668
                     avg_d_RH                NaN            NaN          NaN
                     avg_d_precip            NaN            NaN          NaN
                     avg_d_tmp               NaN            NaN          NaN
                     avg_d_wind              NaN            NaN          NaN
...                                          ...            ...          ...
(64.9631, -19.0208)  data                    NaN        Iceland  73191.11632
                     avg_d_RH                NaN            NaN          NaN
                     avg_d_precip            NaN            NaN          NaN
                     avg_d_tmp               NaN            NaN          NaN
                     avg_d_wind              NaN            NaN          NaN

                                   Urbanization  avg_m_tmp   avg_m_RH  \
coordinate           information
(-41.4545, 145.9707) data                86.012  15.466667  68.818182
                     avg_d_RH               NaN        NaN        NaN
                     avg_d_precip           NaN        NaN        NaN
                     avg_d_tmp              NaN        NaN        NaN
                     avg_d_wind             NaN        NaN        NaN
...                                         ...        ...        ...
(64.9631, -19.0208)  data                93.813  -2.230159  78.571429
                     avg_d_RH               NaN        NaN        NaN
                     avg_d_precip           NaN        NaN        NaN
                     avg_d_tmp              NaN        NaN        NaN
                     avg_d_wind             NaN        NaN        NaN

                                   avg_m_precip  avg_m_wind  Max_Cases  \
coordinate           information
(-41.4545, 145.9707) data                   0.0   18.469697       47.0
                     avg_d_RH               NaN         NaN        NaN
                     avg_d_precip           NaN         NaN        NaN
                     avg_d_tmp              NaN         NaN        NaN
                     avg_d_wind             NaN         NaN        NaN
...                                         ...         ...        ...
(64.9631, -19.0208)  data                   0.0   16.523810      890.0
                     avg_d_RH               NaN         NaN        NaN
                     avg_d_precip           NaN         NaN        NaN
                     avg_d_tmp              NaN         NaN        NaN
                     avg_d_wind             NaN         NaN        NaN

                                    first_7  ... 3/18/2020 3/19/2020  \
coordinate           information             ...
(-41.4545, 145.9707) data          1.333333  ...      10.0      10.0
                     avg_d_RH           NaN  ...      82.0      93.0
                     avg_d_precip       NaN  ...       0.0       0.0
                     avg_d_tmp          NaN  ...      16.5      14.9
                     avg_d_wind         NaN  ...      18.6       8.4
...                                     ...  ...       ...       ...
(64.9631, -19.0208)  data          1.680000  ...     250.0     330.0
                     avg_d_RH           NaN  ...      77.0      75.0
                     avg_d_precip       NaN  ...       0.0       0.0
                     avg_d_tmp          NaN  ...      -1.0      -6.0
                     avg_d_wind         NaN  ...      13.4      13.6

                                  3/20/2020  3/21/2020  3/22/2020  3/23/2020  \
coordinate           information
(-41.4545, 145.9707) data              10.0       16.0       22.0       28.0
                     avg_d_RH          81.0       73.0       68.0       64.0
                     avg_d_precip       0.0        0.0        0.0        0.0
                     avg_d_tmp         14.9       14.1       12.8       10.6
                     avg_d_wind        21.2       13.5       14.4        9.8
...                                     ...        ...        ...        ...
(64.9631, -19.0208)  data             409.0      473.0      568.0      588.0
                     avg_d_RH          67.0       67.0       66.0       69.0
                     avg_d_precip       0.0        0.0        0.0        0.0
                     avg_d_tmp          2.3        2.4        1.9        3.0
                     avg_d_wind        36.3       29.4       27.8       35.3

                                   3/24/2020  3/25/2020  3/26/2020  3/27/2020
coordinate           information
(-41.4545, 145.9707) data               28.0       36.0       47.0       47.0
                     avg_d_RH           74.0       74.0       68.0       74.0
                     avg_d_precip        0.0        0.0        0.0        0.0
                     avg_d_tmp          11.1       12.3       11.2       13.5
                     avg_d_wind         10.1        8.5       15.2        6.8
...                                      ...        ...        ...        ...
(64.9631, -19.0208)  data              648.0      737.0      802.0      890.0
                     avg_d_RH           63.0       62.0       59.0       64.0
                     avg_d_precip        0.0        0.0        0.0        0.0
                     avg_d_tmp           1.6        1.6        1.5       -0.9
                     avg_d_wind         25.6       16.6       24.8       12.5

[895 rows x 84 columns]

In [5]:
# https://data.worldbank.org/indicator/NY.GDP.PCAP.CD  - in current USD
gdp_country_path = '../external_datasets/GDP_per_capita_countries.csv'
# https://en.wikipedia.org/wiki/List_of_U.S._states_by_GDP_per_capita#cite_note-3
gdp_state_path = '../external_datasets/GDP_per_capita_states.csv'
# source: http://wdi.worldbank.org/table/4.2# (2018)
urban_country_path = '../external_datasets/urbanization_data.csv'
# source: US census bureau (most updated was is from 2010)
urban_state_path = '../external_datasets/urbanization_states.csv'

In [6]:
# # source: http://wdi.worldbank.org/table/4.2# (2018)
gdp_country = pd.read_csv(gdp_country_path)
gdp_country.columns=['Country_Region', 'GDP']

# # source: https://www.statista.com/statistics/248023/us-gross-domestic-product-gdp-by-state/ 
gdp_state = pd.read_csv(gdp_state_path)
gdp_state.columns = ['Province_State', 'GDP']

In [7]:
# source: http://wdi.worldbank.org/table/4.2# (2018)
urban_country = pd.read_csv(urban_country_path)
urban_country.columns=['Country_Region', 'Urbanization']

# source: US census bureau (most updated was is from 2010)
urban_state = pd.read_csv(urban_state_path)
urban_state.columns = ['Province_State', 'Urbanization']

In [8]:
def standardize_original_names(df):
    df = df.replace({'Cape Verde': 'Cabo Verde',
                     'Timor-Leste': 'East Timor',
                     'Timor Leste': 'East Timor',
                     'Taiwan*': 'Taiwan'
                    })
    return df

hopkins_conf = standardize_original_names(hopkins_conf)
print(len(hopkins_conf['Country_Region']))
hopkins_conf_countries_set = set(hopkins_conf['Country_Region'].dropna())
print(len(hopkins_conf_countries_set))
hopkins_conf_countries_set

895
124

{'Afghanistan',
 'Albania',
 'Algeria',
 'Andorra',
 'Argentina',
 'Armenia',
 'Australia',
 'Austria',
 'Azerbaijan',
 'Bahrain',
 'Bangladesh',
 'Barbados',
 'Belarus',
 'Belgium',
 'Bolivia',
 'Bosnia and Herzegovina',
 'Brazil',
 'Brunei',
 'Bulgaria',
 'Burkina Faso',
 'Cambodia',
 'Cameroon',
 'Canada',
 'Chile',
 'China',
 'Colombia',
 'Congo (Kinshasa)',
 'Costa Rica',
 "Cote d'Ivoire",
 'Croatia',
 'Cuba',
 'Cyprus',
 'Czechia',
 'Denmark',
 'Dominican Republic',
 'Ecuador',
 'Egypt',
 'Estonia',
 'Finland',
 'France',
 'Georgia',
 'Germany',
 'Ghana',
 'Greece',
 'Guatemala',
 'Guyana',
 'Honduras',
 'Hungary',
 'Iceland',
 'India',
 'Indonesia',
 'Iran',
 'Iraq',
 'Ireland',
 'Israel',
 'Italy',
 'Jamaica',
 'Japan',
 'Jordan',
 'Kazakhstan',
 'Kenya',
 'Korea, South',
 'Kosovo',
 'Kuwait',
 'Kyrgyzstan',
 'Latvia',
 'Lebanon',
 'Liechtenstein',
 'Lithuania',
 'Luxembourg',
 'Madagascar',
 'Malaysia',
 'Mauritius',
 'Mexico',
 'Moldova',
 'Monaco',
 'Montenegro',
 'Morocco',
 'Netherlands',
 'New Zealand',
 'Nigeria',
 'North Macedonia',
 'Norway',
 'Oman',
 'Pakistan',
 'Panama',
 'Paraguay',
 'Peru',
 'Philippines',
 'Poland',
 'Portugal',
 'Qatar',
 'Romania',
 'Russia',
 'Rwanda',
 'San Marino',
 'Saudi Arabia',
 'Senegal',
 'Serbia',
 'Singapore',
 'Slovakia',
 'Slovenia',
 'South Africa',
 'Spain',
 'Sri Lanka',
 'Sweden',
 'Switzerland',
 'Taiwan',
 'Thailand',
 'Togo',
 'Trinidad and Tobago',
 'Tunisia',
 'Turkey',
 'US',
 'Uganda',
 'Ukraine',
 'United Arab Emirates',
 'United Kingdom',
 'Uruguay',
 'Uzbekistan',
 'Venezuela',
 'Vietnam',
 'West Bank and Gaza',
 'Zambia'}

In [9]:
index_dict = {
    'gdp_country': 'Country_Region',
    'gdp_state': 'Province_State',
    'urban_country': 'Country_Region',
    'urban_state': 'Province_State'    
}

In [23]:
def standardize_external_names(external_df):
    external_df = external_df.replace({
        'United States': 'US',
        'Iran, Islamic Rep.': 'Iran',
        'Congo, Rep.': 'Congo (Brazzaville)',
        'Congo, Dem. Rep.': 'Congo (Kinshasa)',
        'St. Lucia': 'Saint Lucia',
        'Czech Republic':'Czechia',
        'Kyrgyz Republic': 'Kyrgyzstan',
        'Egypt, Arab Rep.': 'Egypt',
        'Syrian Arab Republic': 'Syria',
    #     'Cabo Verde': 'Cape Verde',
        'Brunei Darussalam': 'Brunei',
        'Slovak Republic': 'Slovakia',
        'Russian Federation': 'Russia',
        'Korea, Rep.': 'Korea, South',
        'Timor Leste': 'East Timor',
        'Venezuela, RB': 'Venezuela',
        'St. Vincent and the Grenadines': 'Saint Vincent and the Grenadines',
        })
    return external_df

gdp_country = standardize_external_names(gdp_country)
urban_country = standardize_external_names(urban_country)

In [24]:
# setting indices for more convenient access in lambda funtion below
gdp_country = gdp_country.set_index(index_dict['gdp_country'])
gdp_state = gdp_state.set_index(index_dict['gdp_state'])
urban_country = urban_country.set_index(index_dict['urban_country'])
urban_state = urban_state.set_index(index_dict['urban_state'])

In [35]:
gdp_country.at['Iran', 'GDP']

nan

In [36]:
gdp_countries_set = set(gdp_country.index)
# print(len(gdp_countries_set))
urban_countries_set = set(urban_country.index)
# gdp_countries_set

In [12]:
print(len(hopkins_conf_countries_set))
original_minus_gdp = hopkins_conf_countries_set.difference(gdp_countries_set)
original_minus_gdp

124

{'Taiwan'}

In [13]:
print(len(hopkins_conf_countries_set))
original_minus_urban = hopkins_conf_countries_set.difference(urban_countries_set)
print(original_minus_urban)
urban_minus_original = urban_countries_set.difference(hopkins_conf_countries_set)
# urban_minus_original

124
{'Taiwan'}

In [14]:
# gdp_countries_set

In [15]:
# check = test[test['Urbanization'].isna()]
check = hopkins_conf[hopkins_conf['Country_Region'].isna()]
check.shape

(716, 82)

In [16]:
check = test[test['Urbanization'].isna()]
check = check[check['Country_Region'].notna()]
check

,,Province_State,Country_Region,GDP,Urbanization,avg_m_tmp,avg_m_RH,avg_m_precip,avg_m_wind,Max_Cases,first_7,...,3/18/2020,3/19/2020,3/20/2020,3/21/2020,3/22/2020,3/23/2020,3/24/2020,3/25/2020,3/26/2020,3/27/2020
coordinate,information,,,,,,,,,,,,,,,,,,,,,
"(6.4238, -66.5897)",data,NaN,Venezuela,NaN,NaN,32.556061,49.666667,0.0,14.412121,107.0,6.000000,...,36.0,42.0,42.0,70.0,70.0,77.0,84.0,91.0,107.0,107.0
"(23.7, 121.0)",data,NaN,Taiwan,NaN,NaN,18.615152,78.924242,0.0,14.419697,267.0,0.125000,...,100.0,108.0,135.0,153.0,169.0,195.0,215.0,235.0,252.0,267.0
"(42.602636, 20.902977)",data,NaN,Kosovo,4302.276483,NaN,4.912121,64.000000,0.0,12.045455,86.0,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,71.0,86.0
"(60.0, 90.0)",data,NaN,Russia,NaN,NaN,-7.101515,71.909091,0.0,12.530303,1036.0,3.288136,...,147.0,199.0,253.0,306.0,367.0,438.0,495.0,658.0,840.0,1036.0

In [17]:
check = test[test['GDP'].isna()]
check = check[check['Country_Region'].notna()]
check

,,Province_State,Country_Region,GDP,Urbanization,avg_m_tmp,avg_m_RH,avg_m_precip,avg_m_wind,Max_Cases,first_7,...,3/18/2020,3/19/2020,3/20/2020,3/21/2020,3/22/2020,3/23/2020,3/24/2020,3/25/2020,3/26/2020,3/27/2020
coordinate,information,,,,,,,,,,,,,,,,,,,,,
"(6.4238, -66.5897)",data,NaN,Venezuela,NaN,NaN,32.556061,49.666667,0.0,14.412121,107.0,6.000000,...,36.0,42.0,42.0,70.0,70.0,77.0,84.0,91.0,107.0,107.0
"(23.7, 121.0)",data,NaN,Taiwan,NaN,NaN,18.615152,78.924242,0.0,14.419697,267.0,0.125000,...,100.0,108.0,135.0,153.0,169.0,195.0,215.0,235.0,252.0,267.0
"(32.0, 53.0)",data,NaN,Iran,NaN,74.898,12.587879,32.045455,0.0,9.845455,32332.0,2.065497,...,17361.0,18407.0,19644.0,20610.0,21638.0,23049.0,24811.0,27017.0,29406.0,32332.0
"(43.9424, 12.4578)",data,NaN,San Marino,NaN,97.226,8.625758,72.409091,0.0,10.765152,223.0,2.187500,...,119.0,119.0,144.0,144.0,175.0,187.0,187.0,208.0,208.0,223.0
"(47.14, 9.55)",data,NaN,Liechtenstein,NaN,14.338,5.695455,75.924242,0.0,10.057576,56.0,6.000000,...,28.0,28.0,28.0,37.0,37.0,51.0,51.0,51.0,56.0,56.0
"(60.0, 90.0)",data,NaN,Russia,NaN,NaN,-7.101515,71.909091,0.0,12.530303,1036.0,3.288136,...,147.0,199.0,253.0,306.0,367.0,438.0,495.0,658.0,840.0,1036.0

In [19]:
def add_gdp_urban(original, gdp_country, gdp_state, urban_country, urban_state):
    
    original = standardize_original_names(original)

    gdp_country = standardize_external_names(gdp_country)
    urban_country = standardize_external_names(urban_country)
    
    # setting indices for more convenient access in lambda funtion below
    gdp_country = gdp_country.set_index(index_dict['gdp_country'])
    gdp_state = gdp_state.set_index(index_dict['gdp_state'])
    urban_country = urban_country.set_index(index_dict['urban_country'])
    urban_state = urban_state.set_index(index_dict['urban_state'])
    
    # if there is no state data, take country data, and if there is also no country data, put NaN
    original['GDP'] = original.apply(lambda row: gdp_state.loc[row['Province_State'],'GDP'] if row['Province_State'] in list(gdp_state.index) else (gdp_country.loc[row['Country_Region'],'GDP'] if row['Country_Region'] in list(gdp_country.index) else np.NaN), axis=1) 
    original['Urbanization'] = original.apply(lambda row: urban_state.loc[row['Province_State'],'Urbanization'] if row['Province_State'] in list(urban_state.index) else (urban_country.loc[row['Country_Region'],'Urbanization'] if row['Country_Region'] in list(urban_country.index) else np.NaN), axis=1)
    
    new_columns = list(original.columns)
#     print(new_columns)
    prev_GDP = new_columns.index('GDP')
    prev_urban = new_columns.index('Urbanization')

#     print(prev_GDP)
    new_GDP = new_columns.index('Country_Region') + 1
#     print(new_GDP)
    new_urban = new_GDP + 1
    print(new_urban)
#     print(len(new_columns))
    new_columns.insert(new_GDP, new_columns.pop(prev_GDP))
    
    new_columns.insert(new_urban, new_columns.pop(prev_urban))
    
    return original[new_columns]
#     return original