## add_gdp_data notebook

Adds GDP (in billion USD) column to given tableau and hopkins augmented data.

In [1]:
import pandas as pd

In [2]:
tableau_conf_data = pd.read_csv('../augmented_datasets/tableau_conf_data.csv')
tableau_death_data = pd.read_csv('../augmented_datasets/tableau_death_data.csv')

In [3]:
# source: http://wdi.worldbank.org/table/4.2#
GDP_data = pd.read_csv('../external_datasets/MDI_GDP_1.csv')

In [4]:
# source: https://www.statista.com/statistics/248023/us-gross-domestic-product-gdp-by-state/
GDP_states_data = pd.read_csv('../external_datasets/GDP_states_data.csv')

In [5]:
GDP_states_data

          Province_State       GDP
0             California  2,968.12
1                  Texas   1,775.8
2               New York  1,676.35
3                Florida  1,036.32
4               Illinois    864.59
5           Pennsylvania    788.54
6                   Ohio    676.19
7             New Jersey    624.85
8                Georgia    588.17
9          Massachusetts    567.25
10        North Carolina     565.8
11            Washington    563.15
12              Virginia    534.45
13              Michigan    528.01
14              Maryland    412.92
15              Colorado     368.8
16             Minnesota    368.32
17               Indiana    366.71
18             Tennessee     365.6
19               Arizona    346.79
20             Wisconsin    336.97
21              Missouri    317.75
22           Connecticut    274.18
23             Louisiana    252.12
24                Oregon    238.68
25        South Carolina    230.35
26               Alabama    221.13
27              Kentucky    208.34
28              Oklahoma    199.98
29                  Iowa    190.15
30                  Utah    177.34
31                Kansas    167.04
32                Nevada     165.8
33  District of Columbia    140.28
34              Arkansas    128.08
35              Nebraska    122.97
36           Mississippi    114.11
37            New Mexico     99.43
38                Hawaii     92.03
39         New Hampshire     84.71
40         West Virginia     77.48
41                 Idaho        77
42              Delaware     74.97
43                 Maine     64.35
44          Rhode Island     61.02
45          North Dakota     54.71
46                Alaska     54.01
47          South Dakota     51.58
48               Montana     48.97
49               Wyoming     39.37
50               Vermont     33.73

In [6]:
# prepping GDP data to have same Country_Region names as Tableau and Hopkins data

GDP_data.rename(columns = {'Country':'Country_Region'}, inplace = True) 
GDP_data = GDP_data.replace({
#     'United States': 'US',
    'Iran, Islamic Rep.': 'Iran',
    'Congo, Rep.': 'Congo (Brazzaville)',
    'Congo, Dem. Rep.': 'Congo (Kinshasa)',
    'St. Lucia': 'Saint Lucia',
    'Czech Republic':'Czechia',
    'Kyrgyz Republic': 'Kyrgyzstan',
    'Egypt, Arab Rep.': 'Egypt',
    'Syrian Arab Republic': 'Syria',
#     'Cabo Verde': 'Cape Verde',
    'Brunei Darussalam': 'Brunei',
    'Slovak Republic': 'Slovakia',
    'Korea, Rep.': 'Korea, South',
    'Timor Leste': 'East Timor',
    'St. Vincent and the Grenadines': 'Saint Vincent and the Grenadines',
    })
# GDP_data.tail(20)

In [7]:
# print(pd.DataFrame(pd.merge(conf_data, GDP_data, on='Country_Region', how='left')))

In [8]:
def add_GDP_data(df, GDP_data):
    df = df.replace({'Cape Verde': 'Cabo Verde',
                    'Timor-Leste': 'East Timor',
                    'Timor Leste': 'East Timor',
                    'Taiwan*': 'Taiwan'
                    })
    merged_df = df.merge(GDP_data, on='Country_Region', how='left')
    
    merged_df['GDP'][merged_df.Country_Region == 'Taiwan']=589.9

    # Martinique data from 2015, source: https://en.populationdata.net/countries/martinique/
    merged_df['GDP'][merged_df.Country_Region == 'Martinique']=9.363

    # Holy See (aka Vatican City) GDP not available and maybe not relevant?
    # Estimated $21 million for 1999, source: https://www.encyclopedia.com/places/spain-portugal-italy-greece-and-balkans/italian-political-geography/vatican-city
    # merged['GDP'][merged.Country_Region == 'Holy See']=

    # source: https://countryeconomy.com/gdp/venezuela
    merged_df['GDP'][merged_df.Country_Region == 'Venezuela']=98.4

    # source: https://tradingeconomics.com/syria/gdp
    merged_df['GDP'][merged_df.Country_Region == 'Syria']=65

    # source: https://countryeconomy.com/gdp/eritrea
    merged_df['GDP'][merged_df.Country_Region == 'Eritrea']= 2

    return merged_df

In [20]:
def add_GDP_states_data(df, GDP_states_data):

    merged_df = df.merge(GDP_states_data, on='Province_State', how='inner')

    return merged_df

In [24]:
# tableau_conf_gdp = add_GDP_data(tableau_conf_data, GDP_data)
tableau_states_data = pd.merge(tableau_conf_gdp, GDP_states_data, on='Province_State', how='right')
# len(tableau_conf_gdp.GDP.unique())
# tableau_conf_gdp.to_csv('../augmented_datasets/tableau_conf_with_GDP.csv')
tableau_states_data['GDP_x'].unique()

array([nan], dtype=object)

In [17]:
# tableau_conf_GDP_states = pd.merge(tableau_conf_gdp, GDP_states_data, on='Province_State', how='right')
tableau_conf_GDP_states.tail(60)

NameError: name 'tableau_conf_GDP_states' is not defined

In [24]:
pd.get_option("display.max_rows")

60

In [19]:
print(tableau_conf_gdp.Province_State.unique())
print(GDP_states_data.Province_State.unique())

['Arizona' 'California' 'Colorado' 'Connecticut' 'Delaware' 'Florida'
 'Georgia' 'Hawaii' 'Illinois' 'Indiana' 'Iowa' 'Kansas' 'Kentucky'
 'Louisiana' 'Maryland' 'Massachusetts' 'Michigan' 'Minnesota' 'Missouri'
 'Nebraska' 'Nevada' 'New Hampshire' 'New Jersey' 'New Mexico' 'New York'
 'North Carolina' 'Ohio' 'Oklahoma' 'Oregon' 'Pennsylvania' 'Rhode Island'
 'South Carolina' 'South Dakota' 'Tennessee' 'Texas' 'Utah' 'Vermont'
 'Virginia' 'Washington' 'Wisconsin' 'Manitoba' 'Maine' 'Gansu' 'Ningxia'
 'French Polynesia' 'Sichuan' 'Heilongjiang'
 'Australian Capital Territory' 'Sint Maarten' 'Fujian' 'Isle of Man'
 'Idaho' 'Mississippi' 'Denmark' 'Hong Kong' 'Queensland' 'New Brunswick'
 'Hebei' 'Xinjiang' 'Yunnan' 'Western Australia' 'St Martin' 'Curacao'
 'Tianjin' 'Quebec' 'Netherlands' 'France' 'Grand Princess' 'Alabama'
 'Bermuda' 'Montana' 'West Virginia' 'Guizhou' 'Faroe Islands'
 'United Kingdom' 'Diamond Princess' 'French Guiana' 'Nova Scotia'
 'New Caledonia' 'Hunan' 'Liaoning' 'Hainan' 'Macau' 'Henan' 'Guangxi'
 'Arkansas' 'Guam' '0' 'Inner Mongolia' 'Prince Edward Island' 'Victoria'
 'Shaanxi' 'Hubei' 'Anhui' 'Alaska' 'Alberta' 'North Dakota' 'Aruba'
 'Beijing' 'Puerto Rico' 'Reunion' 'Shanghai' 'New South Wales'
 'South Australia' 'Saskatchewan' 'Guangdong' 'Chongqing'
 'Northwest Territories' 'Gibraltar' 'Jilin' 'Guadeloupe' 'Mayotte'
 'Shanxi' 'Ontario' 'Jiangsu' 'District of Columbia' 'Wyoming'
 'Cayman Islands' 'Jiangxi' 'Zhejiang' 'British Columbia'
 'Channel Islands' 'Tasmania' 'Virgin Islands' 'Shandong'
 'Northern Territory' 'Saint Barthelemy' 'Montserrat'
 'Newfoundland and Labrador']
['California' 'Texas' 'New York' 'Florida' 'Illinois' 'Pennsylvania'
 'Ohio' 'New Jersey' 'Georgia' 'Massachusetts' 'North Carolina'
 'Washington' 'Virginia' 'Michigan' 'Maryland' 'Colorado' 'Minnesota'
 'Indiana' 'Tennessee' 'Arizona' 'Wisconsin' 'Missouri' 'Connecticut'
 'Louisiana' 'Oregon' 'South Carolina' 'Alabama' 'Kentucky' 'Oklahoma'
 'Iowa' 'Utah' 'Kansas' 'Nevada' 'District of Columbia' 'Arkansas'
 'Nebraska' 'Mississippi' 'New Mexico' 'Hawaii' 'New Hampshire'
 'West Virginia' 'Idaho' 'Delaware' 'Maine' 'Rhode Island' 'North Dakota'
 'Alaska' 'South Dakota' 'Montana' 'Wyoming' 'Vermont']

In [13]:
tableau_conf_gdp.head()

,Unnamed: 0,Date,Country_Region,Province_State,Case_Type,Cases,Difference,Prep_Flow_Runtime,Latest_Date,Lat,...,avg_wind,avg_precip,avg_m_tmp,avg_m_RH,avg_m_wind,avg_m_precip,max_date,growth_factor,max_cases,GDP
0,0,3/11/2020,US,Arizona,Confirmed,0,0,3/23/2020 8:00:09 AM,3/22/2020,32.0575,...,6.6,0.25,14.913158,48.078947,8.573684,0.681579,3/11/2020,1.000000,0.0,NaN
1,1,2/15/2020,US,Arizona,Confirmed,0,0,3/23/2020 8:00:09 AM,3/22/2020,32.8162,...,1.7,0.00,14.913158,48.078947,8.573684,0.681579,3/08/2020,1.000000,2.0,NaN
2,2,3/17/2020,US,Arizona,Confirmed,0,0,3/23/2020 8:00:09 AM,3/22/2020,32.0575,...,7.7,0.00,14.913158,48.078947,8.573684,0.681579,3/11/2020,1.000000,0.0,NaN
3,3,3/03/2020,US,Arizona,Confirmed,1,0,3/23/2020 8:00:09 AM,3/22/2020,33.2918,...,13.8,0.00,15.981579,55.736842,8.336842,1.570526,3/06/2020,1.189207,2.0,NaN
4,4,3/17/2020,US,Arizona,Confirmed,0,0,3/23/2020 8:00:09 AM,3/22/2020,33.2918,...,9.8,0.00,15.981579,55.736842,8.336842,1.570526,3/06/2020,1.189207,2.0,NaN

In [16]:
tableau_death_gdp = add_GDP_data(tableau_death_data,GDP_data)
tableau_death_gdp.to_csv('../augmented_datasets/tableau_death_with_GDP.csv')

/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':
/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if sys.path[0] == '':
/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [24]:
tableau_death_gdp.head()

,Unnamed: 0,Date,Country_Region,Province_State,Case_Type,Cases,Difference,Prep_Flow_Runtime,Latest_Date,Lat,...,avg_wind,avg_precip,avg_m_tmp,avg_m_RH,avg_m_wind,avg_m_precip,max_date,growth_factor,max_cases,GDP
0,0,3/11/2020,US,Arizona,Deaths,0,0,3/23/2020 8:00:09 AM,3/22/2020,32.0575,...,6.6,0.25,14.913158,48.078947,8.573684,0.681579,3/11/2020,1.0,0.0,20544.3
1,1,2/15/2020,US,Arizona,Deaths,0,0,3/23/2020 8:00:09 AM,3/22/2020,32.8162,...,1.7,0.00,14.913158,48.078947,8.573684,0.681579,2/15/2020,1.0,0.0,20544.3
2,2,3/17/2020,US,Arizona,Deaths,0,0,3/23/2020 8:00:09 AM,3/22/2020,32.0575,...,7.7,0.00,14.913158,48.078947,8.573684,0.681579,3/11/2020,1.0,0.0,20544.3
3,3,3/3/2020,US,Arizona,Deaths,0,0,3/23/2020 8:00:09 AM,3/22/2020,33.2918,...,13.8,0.00,15.981579,55.736842,8.336842,1.570526,3/3/2020,1.0,0.0,20544.3
4,4,3/17/2020,US,Arizona,Deaths,0,0,3/23/2020 8:00:09 AM,3/22/2020,33.2918,...,9.8,0.00,15.981579,55.736842,8.336842,1.570526,3/3/2020,1.0,0.0,20544.3

In [17]:
hopkins_conf_data = pd.read_csv('../augmented_datasets/hopkins_conf_augmented2803.csv')
hopkins_death_data = pd.read_csv('../augmented_datasets/hopkins_conf_augmented2803.csv')

In [18]:
hopkins_conf_gdp = add_GDP_data(hopkins_conf_data,GDP_data)
hopkins_conf_gdp.to_csv('../augmented_datasets/hopkins_conf_with_GDP.csv')

/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':
/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if sys.path[0] == '':
/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [23]:
hopkins_conf_gdp.head()

,Unnamed: 0,weather,Province_State,Country_Region,avg_m_tmp,avg_m_RH,avg_m_precip,avg_m_wind,Max_Cases,Max_Date,...,3/19/2020,3/20/2020,3/21/2020,3/22/2020,3/23/2020,3/24/2020,3/25/2020,3/26/2020,3/27/2020,GDP
0,"(-41.4545, 145.9707)",data,Tasmania,Australia,15.466667,68.818182,0.0,18.469697,47.0,3/26/2020,...,10.0,10.0,16.0,22.0,28.0,28.0,36.0,47.0,47.0,1433.9
1,"(-41.4545, 145.9707)",avg_d_RH,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,93.0,81.0,73.0,68.0,64.0,74.0,74.0,68.0,74.0,NaN
2,"(-41.4545, 145.9707)",avg_d_precip,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
3,"(-41.4545, 145.9707)",avg_d_tmp,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,14.9,14.9,14.1,12.8,10.6,11.1,12.3,11.2,13.5,NaN
4,"(-41.4545, 145.9707)",avg_d_wind,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,8.4,21.2,13.5,14.4,9.8,10.1,8.5,15.2,6.8,NaN

In [19]:
hopkins_death_gdp = add_GDP_data(hopkins_death_data,GDP_data)
hopkins_death_gdp.to_csv('../augmented_datasets/hopkins_death_with_GDP.csv')

/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':
/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if sys.path[0] == '':
/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [22]:
hopkins_death_gdp.head()

,Unnamed: 0,weather,Province_State,Country_Region,avg_m_tmp,avg_m_RH,avg_m_precip,avg_m_wind,Max_Cases,Max_Date,...,3/19/2020,3/20/2020,3/21/2020,3/22/2020,3/23/2020,3/24/2020,3/25/2020,3/26/2020,3/27/2020,GDP
0,"(-41.4545, 145.9707)",data,Tasmania,Australia,15.466667,68.818182,0.0,18.469697,47.0,3/26/2020,...,10.0,10.0,16.0,22.0,28.0,28.0,36.0,47.0,47.0,1433.9
1,"(-41.4545, 145.9707)",avg_d_RH,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,93.0,81.0,73.0,68.0,64.0,74.0,74.0,68.0,74.0,NaN
2,"(-41.4545, 145.9707)",avg_d_precip,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
3,"(-41.4545, 145.9707)",avg_d_tmp,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,14.9,14.9,14.1,12.8,10.6,11.1,12.3,11.2,13.5,NaN
4,"(-41.4545, 145.9707)",avg_d_wind,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,8.4,21.2,13.5,14.4,9.8,10.1,8.5,15.2,6.8,NaN